tap 'github/bootstrap'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'homebrew/cask-fonts'
tap 'apparition47/tap'

brew 'asdf'
brew 'bat'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'gnupg'
brew 'gti'
brew 'httpie'
brew 'jq'
brew 'less'
brew 'mas'
brew 'node-build'
brew 'pinentry-mac'
brew 'ripgrep'
brew 'ruby-build'
brew 'sl'
brew 'neovim'

cask '1password'
cask '1password-cli'
cask 'Kitty'
cask 'Alfred'
cask 'Dash'
cask 'Hazel'
cask 'Obsidian'
cask 'Quitter'
cask 'Stay'
cask 'Tailscale'

mas 'Drafts', id: 1435957248
mas 'RunCat', id: 1429033973
